# History Navigator Configuration

# History file sources
sources:
  - ~/.zsh_history
  - ~/.bash_history

# Patterns to exclude from history (regex)
exclude_patterns:
  - "^sudo su"          # sudo su commands (but not all sudo)  
  - "password"
  - "token"
  - "secret"
  - "key.*="           # environment variables with keys
  - "^history"
  - "^exit$"
  - "^clear$"
  - "^pwd$"
  - "^\\.$"
  - "^\\.\\.+$"
  - "^\\d+$"              # Just numbers
  - "^[[:space:]]*$"     # Just whitespace
  - "h$"

# UI settings
ui:
  max_items: 1000
  theme: "dark"
  show_timestamps: true
  show_frequency: true

# Templates file path
templates_path: "~/.config/history-nav/templates.yaml"

# Performance settings
performance:
  cache_enabled: true
  max_history_lines: 10000